In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df_telco=pd.read_csv("/content/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [ ]:
df_telco.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [ ]:
df_telco.shape

(7043, 21)

In [ ]:
df_telco.describe

<bound method NDFrame.describe of       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95        1889.5
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40         306.6
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
0       No
1       No
2      Yes
3       No
4      Yes
...    ...
7038    No
7039    No
7040    No
7041   Yes
7042    No

[7043 rows x 21 columns]>

In [ ]:
df_telco.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [ ]:
customer_5=df_telco.iloc[0:,0:5]
print(customer_5)

      customerID  gender  SeniorCitizen Partner Dependents
0     7590-VHVEG  Female              0     Yes         No
1     5575-GNVDE    Male              0      No         No
2     3668-QPYBK    Male              0      No         No
3     7795-CFOCW    Male              0      No         No
4     9237-HQITU  Female              0      No         No
...          ...     ...            ...     ...        ...
7038  6840-RESVB    Male              0     Yes        Yes
7039  2234-XADUH  Female              0     Yes        Yes
7040  4801-JZAZL  Female              0     Yes        Yes
7041  8361-LTMKD    Male              1     Yes         No
7042  3186-AJIEK    Male              0      No         No

[7043 rows x 5 columns]

In [ ]:
customer_15=df_telco.iloc[0:,6:21]
print(customer_15)

     PhoneService     MultipleLines InternetService OnlineSecurity  \
0              No  No phone service             DSL             No
1             Yes                No             DSL            Yes
2             Yes                No             DSL            Yes
3              No  No phone service             DSL            Yes
4             Yes                No     Fiber optic             No
...           ...               ...             ...            ...
7038          Yes               Yes             DSL            Yes
7039          Yes               Yes     Fiber optic             No
7040           No  No phone service             DSL            Yes
7041          Yes               Yes     Fiber optic             No
7042          Yes                No     Fiber optic            Yes

     OnlineBackup DeviceProtection TechSupport StreamingTV StreamingMovies  \
0             Yes               No          No          No              No
1              No              Yes          No          No              No
2             Yes               No          No          No              No
3              No              Yes         Yes          No              No
4              No               No          No          No              No
...           ...              ...         ...         ...             ...
7038           No              Yes         Yes         Yes             Yes
7039          Yes              Yes          No         Yes             Yes
7040           No               No          No          No              No
7041           No               No          No          No              No
7042           No              Yes         Yes         Yes             Yes

            Contract PaperlessBilling              PaymentMethod  \
0     Month-to-month              Yes           Electronic check
1           One year               No               Mailed check
2     Month-to-month              Yes               Mailed check
3           One year               No  Bank transfer (automatic)
4     Month-to-month              Yes           Electronic check
...              ...              ...                        ...
7038        One year              Yes               Mailed check
7039        One year              Yes    Credit card (automatic)
7040  Month-to-month              Yes           Electronic check
7041  Month-to-month              Yes               Mailed check
7042        Two year              Yes  Bank transfer (automatic)

      MonthlyCharges TotalCharges Churn
0              29.85        29.85    No
1              56.95       1889.5    No
2              53.85       108.15   Yes
3              42.30      1840.75    No
4              70.70       151.65   Yes
...              ...          ...   ...
7038           84.80       1990.5    No
7039          103.20       7362.9    No
7040           29.60       346.45    No
7041           74.40        306.6   Yes
7042          105.65       6844.5    No

[7043 rows x 15 columns]

In [ ]:
senior_male_electronic=df_telco[(df_telco['gender']=='Male')& (df_telco['SeniorCitizen']==1)&(df_telco['PaymentMethod']=='Electronic check')]
print(senior_male_electronic)

      customerID gender  SeniorCitizen Partner Dependents  tenure  \
20    8779-QRDMV   Male              1      No         No       1
55    1658-BYGOY   Male              1      No         No      18
57    5067-XJQFU   Male              1     Yes        Yes      66
78    0191-ZHSKZ   Male              1      No         No      30
91    2424-WVHPL   Male              1      No         No       1
...          ...    ...            ...     ...        ...     ...
6837  6229-LSCKB   Male              1      No         No       6
6894  1400-MMYXY   Male              1     Yes         No       3
6914  7142-HVGBG   Male              1     Yes         No      43
6967  8739-WWKDU   Male              1      No         No      25
7032  6894-LFHLY   Male              1      No         No       1

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
20             No  No phone service             DSL             No  ...
55            Yes               Yes     Fiber optic             No  ...
57            Yes               Yes     Fiber optic             No  ...
78            Yes                No             DSL            Yes  ...
91            Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
6837          Yes                No     Fiber optic             No  ...
6894          Yes               Yes     Fiber optic             No  ...
6914          Yes               Yes     Fiber optic             No  ...
6967          Yes               Yes     Fiber optic             No  ...
7032          Yes               Yes     Fiber optic             No  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
20                Yes          No          No             Yes  Month-to-month
55                 No          No         Yes             Yes  Month-to-month
57                Yes         Yes         Yes             Yes        One year
78                 No          No         Yes             Yes  Month-to-month
91                 No         Yes          No              No  Month-to-month
...               ...         ...         ...             ...             ...
6837               No          No         Yes              No  Month-to-month
6894              Yes          No         Yes             Yes  Month-to-month
6914              Yes          No         Yes             Yes  Month-to-month
6967               No          No         Yes              No  Month-to-month
7032               No          No          No              No  Month-to-month

     PaperlessBilling     PaymentMethod MonthlyCharges  TotalCharges Churn
20                Yes  Electronic check          39.65         39.65   Yes
55                Yes  Electronic check          95.45       1752.55   Yes
57                Yes  Electronic check         108.45       7076.35    No
78                Yes  Electronic check          74.75        2111.3    No
91                 No  Electronic check          74.70          74.7    No
...               ...               ...            ...           ...   ...
6837              Yes  Electronic check          79.70         497.6    No
6894              Yes  Electronic check         105.90        334.65   Yes
6914              Yes  Electronic check         103.00        4414.3   Yes
6967              Yes  Electronic check          89.50       2196.15   Yes
7032              Yes  Electronic check          75.75         75.75   Yes

[298 rows x 21 columns]

In [ ]:
customer_total_tenure=df_telco[(df_telco['tenure'] > 70) | (df_telco['MonthlyCharges']> 100)]
print(customer_total_tenure)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
8     7892-POOKP  Female              0     Yes         No      28
12    8091-TTVAX    Male              0     Yes         No      58
13    0280-XJGEX    Male              0      No         No      49
14    5129-JLPIS    Male              0      No         No      25
15    3655-SNQYZ  Female              0     Yes        Yes      69
...          ...     ...            ...     ...        ...     ...
7023  1035-IPQPU  Female              1     Yes         No      63
7034  0639-TSIQW  Female              0      No         No      67
7037  2569-WGERO  Female              0      No         No      72
7039  2234-XADUH  Female              0     Yes        Yes      72
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
8             Yes           Yes     Fiber optic                   No  ...
12            Yes           Yes     Fiber optic                   No  ...
13            Yes           Yes     Fiber optic                   No  ...
14            Yes            No     Fiber optic                  Yes  ...
15            Yes           Yes     Fiber optic                  Yes  ...
...           ...           ...             ...                  ...  ...
7023          Yes           Yes     Fiber optic                   No  ...
7034          Yes           Yes     Fiber optic                  Yes  ...
7037          Yes            No              No  No internet service  ...
7039          Yes           Yes     Fiber optic                   No  ...
7042          Yes            No     Fiber optic                  Yes  ...

         DeviceProtection          TechSupport          StreamingTV  \
8                     Yes                  Yes                  Yes
12                    Yes                   No                  Yes
13                    Yes                   No                  Yes
14                    Yes                  Yes                  Yes
15                    Yes                  Yes                  Yes
...                   ...                  ...                  ...
7023                  Yes                   No                  Yes
7034                  Yes                   No                  Yes
7037  No internet service  No internet service  No internet service
7039                  Yes                   No                  Yes
7042                  Yes                  Yes                  Yes

          StreamingMovies        Contract PaperlessBilling  \
8                     Yes  Month-to-month              Yes
12                    Yes        One year               No
13                    Yes  Month-to-month              Yes
14                    Yes  Month-to-month              Yes
15                    Yes        Two year               No
...                   ...             ...              ...
7023                  Yes  Month-to-month              Yes
7034                   No  Month-to-month              Yes
7037  No internet service        Two year              Yes
7039                  Yes        One year              Yes
7042                  Yes        Two year              Yes

                  PaymentMethod MonthlyCharges  TotalCharges Churn
8              Electronic check         104.80       3046.05   Yes
12      Credit card (automatic)         100.35        5681.1    No
13    Bank transfer (automatic)         103.70        5036.3   Yes
14             Electronic check         105.50       2686.05    No
15      Credit card (automatic)         113.25       7895.15    No
...                         ...            ...           ...   ...
7023           Electronic check         103.50        6479.4    No
7034    Credit card (automatic)         102.95       6886.25   Yes
7037  Bank transfer (automatic)          21.15        1419.4    No
7039    Credit card (automatic)         103.20        7362.9    No
7042  Bank transfer (automatic)         105.65        6844.5    No

[1259 rows x 21 columns]

In [ ]:
two_mail_yes=df_telco[(df_telco['Contract']=='Two year')&(df_telco['PaymentMethod']=='Mailed check')&(df_telco['Churn']=='Yes')]
print(two_mail_yes)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
268   6323-AYBRX    Male              0      No         No      59
5947  7951-QKZPL  Female              0     Yes        Yes      33
6680  9412-ARGBX  Female              0      No        Yes      48

     PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
268           Yes            No              No  No internet service  ...
5947          Yes           Yes              No  No internet service  ...
6680          Yes            No     Fiber optic                   No  ...

         DeviceProtection          TechSupport          StreamingTV  \
268   No internet service  No internet service  No internet service
5947  No internet service  No internet service  No internet service
6680                  Yes                  Yes                  Yes

          StreamingMovies  Contract PaperlessBilling PaymentMethod  \
268   No internet service  Two year               No  Mailed check
5947  No internet service  Two year              Yes  Mailed check
6680                   No  Two year              Yes  Mailed check

     MonthlyCharges  TotalCharges Churn
268           19.35        1099.6   Yes
5947          24.50         740.3   Yes
6680          95.50       4627.85   Yes

[3 rows x 21 columns]

In [ ]:
streaming=df_telco[(df_telco['StreamingTV']=='Yes')| (df_telco['StreamingMovies']=='Yes')]
print(streaming)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
5     9305-CDSKC  Female              0      No         No       8
6     1452-KIOVK    Male              0      No        Yes      22
8     7892-POOKP  Female              0     Yes         No      28
12    8091-TTVAX    Male              0     Yes         No      58
13    0280-XJGEX    Male              0      No         No      49
...          ...     ...            ...     ...        ...     ...
7035  8456-QDAVC    Male              0      No         No      19
7036  7750-EYXWZ  Female              0      No         No      12
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
5             Yes               Yes     Fiber optic             No  ...
6             Yes               Yes     Fiber optic             No  ...
8             Yes               Yes     Fiber optic             No  ...
12            Yes               Yes     Fiber optic             No  ...
13            Yes               Yes     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7035          Yes                No     Fiber optic             No  ...
7036           No  No phone service             DSL             No  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
5                 Yes          No         Yes             Yes  Month-to-month
6                  No          No         Yes              No  Month-to-month
8                 Yes         Yes         Yes             Yes  Month-to-month
12                Yes          No         Yes             Yes        One year
13                Yes          No         Yes             Yes  Month-to-month
...               ...         ...         ...             ...             ...
7035               No          No         Yes              No  Month-to-month
7036              Yes         Yes         Yes             Yes        One year
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
5                 Yes           Electronic check          99.65         820.5
6                 Yes    Credit card (automatic)          89.10        1949.4
8                 Yes           Electronic check         104.80       3046.05
12                 No    Credit card (automatic)         100.35        5681.1
13                Yes  Bank transfer (automatic)         103.70        5036.3
...               ...                        ...            ...           ...
7035              Yes  Bank transfer (automatic)          78.70        1495.1
7036               No           Electronic check          60.65         743.3
7038              Yes               Mailed check          84.80        1990.5
7039              Yes    Credit card (automatic)         103.20        7362.9
7042              Yes  Bank transfer (automatic)         105.65        6844.5

     Churn
5      Yes
6       No
8      Yes
12      No
13     Yes
...    ...
7035    No
7036    No
7038    No
7039    No
7042    No

[3499 rows x 21 columns]

In [ ]:
female_dsl=df_telco[(df_telco['gender']=='Female')& (df_telco['InternetService']=='DSL')]
print(female_dsl)

      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
7     6713-OKOMC  Female              0      No         No      10
18    4190-MFLUW  Female              0     Yes        Yes      10
23    3638-WEABW  Female              0     Yes         No      58
25    6865-JZNKO  Female              0      No         No      30
...          ...     ...            ...     ...        ...     ...
7026  8775-CEBBJ  Female              0      No         No       9
7028  9281-CEDRU  Female              0     Yes         No      68
7029  2235-DWLJU  Female              1      No         No       6
7036  7750-EYXWZ  Female              0      No         No      12
7040  4801-JZAZL  Female              0     Yes        Yes      11

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
7              No  No phone service             DSL            Yes  ...
18            Yes                No             DSL             No  ...
23            Yes               Yes             DSL             No  ...
25            Yes                No             DSL            Yes  ...
...           ...               ...             ...            ...  ...
7026          Yes                No             DSL             No  ...
7028          Yes                No             DSL             No  ...
7029           No  No phone service             DSL             No  ...
7036           No  No phone service             DSL             No  ...
7040           No  No phone service             DSL            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
7                  No          No          No              No  Month-to-month
18                Yes         Yes          No              No  Month-to-month
23                 No         Yes          No              No        Two year
25                 No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7026               No          No          No              No  Month-to-month
7028               No         Yes         Yes              No        Two year
7029               No          No         Yes             Yes  Month-to-month
7036              Yes         Yes         Yes             Yes        One year
7040               No          No          No              No  Month-to-month

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
7                  No               Mailed check          29.75         301.9
18                 No    Credit card (automatic)          55.20        528.35
23                Yes    Credit card (automatic)          59.90        3505.1
25                Yes  Bank transfer (automatic)          55.30        1530.6
...               ...                        ...            ...           ...
7026              Yes  Bank transfer (automatic)          44.20        403.35
7028               No  Bank transfer (automatic)          64.10       4326.25
7029              Yes           Electronic check          44.40        263.05
7036               No           Electronic check          60.65         743.3
7040              Yes           Electronic check          29.60        346.45

     Churn
0       No
7       No
18     Yes
23      No
25      No
...    ...
7026   Yes
7028    No
7029    No
7036    No
7040    No

[1188 rows x 21 columns]

In [ ]:
number=df_telco.shape
print(type(number))

<class 'tuple'>

In [ ]:
print(f"number of rows= {number[0]} and number of columns={number[1]}")

number of rows= 7043 and number of columns=21

In [ ]:
customer_333=df_telco.sample(n=333)
customer_333

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
5584,6330-JKLPC,Male,0,Yes,No,11,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),80.50,896.9,Yes
4613,6987-XQSJT,Female,1,No,No,54,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,79.50,4370.25,Yes
3994,0406-BPDVR,Female,1,Yes,No,54,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,One year,Yes,Credit card (automatic),101.50,5373.1,Yes
5465,6933-FHBZC,Female,0,No,No,26,Yes,No,DSL,No,...,Yes,No,No,No,One year,Yes,Mailed check,56.05,1553.2,No
4207,8706-HRADD,Male,0,No,No,21,No,No phone service,DSL,Yes,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,43.55,1011.5,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1317,9277-JOOMO,Female,0,No,No,3,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,24.60,86.35,No
4704,1928-BXYIV,Male,0,No,No,1,Yes,Yes,DSL,Yes,...,No,No,No,No,Month-to-month,No,Electronic check,61.15,61.15,No
2295,2672-DZUOY,Male,0,No,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,25.15,25.15,Yes
5005,2359-QWQUL,Female,0,Yes,No,39,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Credit card (automatic),104.70,4134.85,Yes
5816,0374-IOEGQ,Female,0,No,No,3,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,44.60,122.7,No

In [ ]:
df_telco['Churn'].value_counts()

<bound method IndexOpsMixin.value_counts of 0        No
1        No
2       Yes
3        No
4       Yes
       ...
7038     No
7039     No
7040     No
7041    Yes
7042     No
Name: Churn, Length: 7043, dtype: object>

In [ ]:
customer_total_tenure.to_csv('customer.csv')

## used cars in uk

In [3]:
df_cars=pd.read_csv('/content/used_cars_UK.csv')

In [4]:
df_cars.head()

,Unnamed: 0,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,0,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
1,1,Vauxhall Corsa,1495,88585,2008,4.0,Petrol,Hatchback,1.2L,Manual,3.0,5.0,Euro 4,Full
2,2,Hyundai i30,949,137000,2011,NaN,Petrol,Hatchback,1.4L,Manual,5.0,5.0,Euro 5,NaN
3,3,MINI Hatch,2395,96731,2010,5.0,Petrol,Hatchback,1.4L,Manual,3.0,4.0,Euro 4,Full
4,4,Vauxhall Corsa,1000,85000,2013,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN

In [6]:
df_cars.shape

(3685, 14)

In [7]:
budget_cars=df_cars[(df_cars['Price']>5000)&(df_cars['Mileage(miles)']>50000)]
budget_cars

,Unnamed: 0,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,0,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
12,12,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
13,14,BMW 3 Series,19800,69690,2019,1.0,Petrol Plug-in Hybrid,Saloon,2.0L,Automatic,4.0,5.0,Euro 6,NaN
21,22,Mercedes-Benz A180,14498,53055,2019,NaN,Petrol,Hatchback,1.3L,Manual,5.0,5.0,Euro 6,NaN
25,26,Mercedes-Benz A Class,15900,62402,2019,1.0,Petrol,Hatchback,1.3L,Automatic,5.0,5.0,Euro 6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3596,4628,SEAT Leon,5495,128000,2013,1.0,Diesel,Hatchback,2.0L,Manual,5.0,5.0,Euro 5,NaN
3600,4635,SEAT Leon,5495,128000,2013,1.0,Diesel,Hatchback,2.0L,Manual,5.0,5.0,Euro 5,NaN
3625,4664,Vauxhall Astra GTC,7495,50312,2015,3.0,Petrol,Coupe,1.4L,Manual,3.0,5.0,Euro 6,NaN
3638,4678,Nissan Qashqai,7995,67000,2015,3.0,Petrol,SUV,1.2L,Manual,5.0,5.0,Euro 5,NaN
3681,4724,Audi A4,6990,119000,2012,NaN,Petrol,Saloon,2.0L,Manual,4.0,5.0,Euro 5,NaN

In [9]:
diesel_hatchback=df_cars[(df_cars['Body type']=='Hatchback')&(df_cars['Fuel type']=='Diesel')]
diesel_hatchback

,Unnamed: 0,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,0,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
4,4,Vauxhall Corsa,1000,85000,2013,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN
9,9,Peugeot 207,1299,87000,2008,5.0,Diesel,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN
10,10,Ford Fiesta,1495,181693,2009,NaN,Diesel,Hatchback,1.6L,Manual,3.0,5.0,Euro 4,Full
12,12,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3654,4695,Vauxhall Corsa,1995,126000,2013,2.0,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN
3656,4697,Toyota Auris,1295,158469,2008,4.0,Diesel,Hatchback,2.0L,Manual,5.0,5.0,Euro 4,NaN
3669,4711,Renault Megane,2489,129000,2013,4.0,Diesel,Hatchback,1.5L,Manual,5.0,5.0,Euro 5,NaN
3670,4712,Fiat Idea,1295,84000,2007,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 4,NaN
3678,4721,Citroen C3,1795,85962,2009,NaN,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 4,NaN

In [10]:
cars=df_cars[(df_cars['Body type']=='Hatchback')&(df_cars['Gearbox']=='Manual')|(df_cars['Body type']=='MPV')&(df_cars['Gearbox']=='Automatic')]
cars

,Unnamed: 0,title,Price,Mileage(miles),Registration_Year,Previous Owners,Fuel type,Body type,Engine,Gearbox,Doors,Seats,Emission Class,Service history
0,0,SKODA Fabia,6900,70189,2016,3.0,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 6,NaN
1,1,Vauxhall Corsa,1495,88585,2008,4.0,Petrol,Hatchback,1.2L,Manual,3.0,5.0,Euro 4,Full
2,2,Hyundai i30,949,137000,2011,NaN,Petrol,Hatchback,1.4L,Manual,5.0,5.0,Euro 5,NaN
3,3,MINI Hatch,2395,96731,2010,5.0,Petrol,Hatchback,1.4L,Manual,3.0,4.0,Euro 4,Full
4,4,Vauxhall Corsa,1000,85000,2013,NaN,Diesel,Hatchback,1.3L,Manual,5.0,5.0,Euro 5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,4717,Vauxhall Astra,4999,60139,2015,2.0,Petrol,Hatchback,1.6L,Manual,5.0,5.0,Euro 6,NaN
3678,4721,Citroen C3,1795,85962,2009,NaN,Diesel,Hatchback,1.4L,Manual,5.0,5.0,Euro 4,NaN
3679,4722,Nissan Qashqai,1695,104000,2009,3.0,Petrol,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN
3680,4723,Renault Megane,1395,76202,2006,4.0,Petrol,Hatchback,1.6L,Manual,5.0,5.0,Euro 4,NaN
3684,4727,Vauxhall Corsa,2000,82160,2013,7.0,Petrol,Hatchback,1.2L,Manual,5.0,5.0,Euro 5,NaN

In [16]:
count=(df_cars['Registration_Year']>=2015).value_counts()
count

False    2555
True     1130
Name: Registration_Year, dtype: int64